# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/HoangNam/python-app/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 600)
        MainWindow.setStyleSheet("padding: 10px;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    background-color: white;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.widget.setStyleSheet("    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                                stop: 0 #e0f7ff, stop: 1 #ffffff);\n"
"    font-family: \"Arial\";\n"
"    font-size: 14px;\n"
"    color: #333333;")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(150, 50, 501, 501))
        self.widget_2.setStyleSheet("background-color: transparent")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setGeometry(QtCore.QRect(60, 100, 391, 81))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;\n"
"font: 16pt \"Sans Serif Collection\";\n"
"background-color:#e0f7ff;\n"
"background:none;")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(120, 190, 261, 41))
        self.lineEdit.setStyleSheet("\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 18px;\n"
"\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 260, 261, 41))
        self.lineEdit_2.setStyleSheet("\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 18px;\n"
" \n"
"    font-size: 14px;\n"
"    color: #333;\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 380, 261, 51))
        self.pushButton_2.setStyleSheet("background-color:#000000;\n"
"font: 12pt \"Times New Roman\";\n"
"color:#ffffff;\n"
"border-radius: 24px;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(270, 310, 111, 41))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("font: 8pt \"Segoe UI\";\n"
"border: none;\n"
"background-color: #ffffff;\n"
"background:none;")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(210, 40, 71, 71))
        self.label_4.setStyleSheet("background:none;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/HoangNam/python-app/ui/../img/weather icon.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 260, 41, 41))
        self.pushButton_3.setStyleSheet("border:none")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/HoangNam/python-app/ui/../img/eye_close-removebg-preview.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 340, 191, 41))
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("font: 8pt \"Segoe UI\";\n"
"border: none;\n"
"background-color: #ffffff;\n"
"background: none;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.label_4.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "                SIGN IN WITH EMAIL"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Email"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton_2.setText(_translate("MainWindow", "SIGN IN"))
        self.pushButton.setText(_translate("MainWindow", "forgot password?"))
        self.pushButton_4.setText(_translate("MainWindow", "Don\'t have an account? Sign Up"))
