# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/HoangNam/python-app/ui/register.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("padding: 10px;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    background-color: white;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 511))
        self.widget.setStyleSheet("    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, \n"
"                                stop: 0 #e0f7ff, stop: 1 #ffffff);\n"
"    font-family: \"Arial\";\n"
"    font-size: 14px;\n"
"    color: #333333;")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(120, 10, 591, 481))
        self.widget_2.setStyleSheet("background-color: transparent")
        self.widget_2.setObjectName("widget_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 160, 261, 41))
        self.lineEdit_3.setStyleSheet("background-color: #f9f9f9;\n"
"border-radius:18px;\n"
"font-size: 14px;\n"
"color: #333;\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(160, 210, 261, 41))
        self.lineEdit.setStyleSheet("\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 18px;\n"
"\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 260, 261, 41))
        self.lineEdit_2.setStyleSheet("\n"
"    background-color: #f9f9f9;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 18px;\n"
"\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(230, 350, 191, 41))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("font: 8pt \"Segoe UI\";\n"
"border: none;\n"
"background-color: #ffffff;\n"
"background: none;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 390, 261, 51))
        self.pushButton_2.setStyleSheet("background-color:#000000;\n"
"font: 12pt \"Times New Roman\";\n"
"color:#ffffff;\n"
"border-radius:24px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        self.label.setGeometry(QtCore.QRect(90, 100, 391, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;\n"
"font: 16pt \"Segoe UI\";\n"
"background-color:#e0f7ff;\n"
"background:none;\n"
"")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(250, 30, 71, 71))
        self.label_5.setStyleSheet("background:none")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/HoangNam/python-app/ui/../img/weather icon.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 310, 261, 41))
        self.lineEdit_4.setStyleSheet("    background-color: #f9f9f9;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 18px;\n"
"\n"
"    font-size: 14px;\n"
"    color: #333;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 270, 31, 24))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 260, 41, 41))
        self.pushButton_4.setStyleSheet("border:none")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/HoangNam/python-app/ui/../img/eye_close-removebg-preview.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(370, 310, 41, 41))
        self.pushButton_5.setStyleSheet("border:none")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Name"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Email"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "Already have an account? Sign In"))
        self.pushButton_2.setText(_translate("MainWindow", "SIGN UP"))
        self.label.setText(_translate("MainWindow", "              SIGN UP WITH EMAIL"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Comfirm password"))
